# -*- coding: utf-8 -*-
"""EXP025c_v5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UnhReoqEhngMUETyVGtEHiMQAoObSsoR
"""

#!/usr/bin/env python3
"""
exp025c-v6-rebuild.py (v4)

Staged search for 1D revivals.

Key design:
  - Two tolerance levels:
      TOL_ACCEPT = 1e-6 : what counts as a numerically verified revival
      TOL_FAMILY = 1e-10: what counts as "part of a family" (tight)
  - Grid hits are checked for isolation too, not just refined hits.
  - Continuous families are collapsed to a single representative.

Run in Colab.
"""

import json
import math
from fractions import Fraction
from pathlib import Path

import numpy as np
from scipy.optimize import minimize_scalar

# ---------------------------------------------------------------------------
# Output location
# ---------------------------------------------------------------------------

DRIVE_REPO = Path("/content/drive/MyDrive/modular-latex")
ROOT = DRIVE_REPO if DRIVE_REPO.exists() else Path("/content")
OUT_JSON = ROOT / "exp025c-v6-output.json"
OUT_TEX  = ROOT / "exp025c-v6-table.tex"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

QUICK_TEST      = False
QUICK_K         = 5        # which k to test if QUICK_TEST is True

N_MAX           = 60
RHO_STEPS       = 10000
TOL_ACCEPT      = 1e-10     # numerical verification threshold
TOL_FAMILY      = 1e-10    # family / isolation threshold (tight)
SEED_TOL        = 1e-3     # residual threshold for triggering refinement
DEDUP_RHO       = 1e-4
DEDUP_DELTA     = 1e-8
ISOLATION_WIDTH = 0.05

DELTA_MULTIPLES = [
    Fraction(0), Fraction(1, 6), Fraction(1, 4), Fraction(1, 3),
    Fraction(1, 2), Fraction(2, 3), Fraction(3, 4), Fraction(5, 6),
    Fraction(1, 1),
    Fraction(2, 5), Fraction(4, 5), Fraction(6, 5), Fraction(8, 5),
    Fraction(5, 4), Fraction(4, 3), Fraction(3, 2),
    Fraction(5, 3), Fraction(7, 4), Fraction(11, 6),
    Fraction(2, 1),
]
DELTA_LIST = [float(m) * math.pi for m in DELTA_MULTIPLES]

KNOWN_REVIVALS = [
    # k = 2 (family representative + isolated)
    (2, 0.5, 0.0, 2),
    (2, 0.25, math.pi, 6),
    (2, 0.5, math.pi, 8),
    (2, 0.75, math.pi, 12),
    (2, 0.5, math.pi/2, 24),
    (2, 0.5, 3*math.pi/2, 24),

    # k = 3
    (3, 2.0/3.0, 0.0, 8),
    (3, (5 - math.sqrt(5))/6, 0.0, 10),
    (3, 1.0/3.0, 0.0, 12),
    (3, 1.0/3.0, 2*math.pi/3, 12),
    (3, 1.0/3.0, 4*math.pi/3, 12),
    (3, (2 - math.sqrt(2))/3, 0.0, 16),
    (3, (3 - math.sqrt(5))/6, 0.0, 20),
    (3, (3 + math.sqrt(5))/6, 0.0, 20),
    (3, (2 - math.sqrt(3))/3, 0.0, 24),
    (3, 2.0/3.0, 2*math.pi/3, 24),
    (3, 2.0/3.0, 4*math.pi/3, 24),
    (3, (5 - math.sqrt(5))/6, 2*math.pi/3, 30),
    (3, (5 - math.sqrt(5))/6, 4*math.pi/3, 30),

    # k = 4
    (4, 0.75, 0.0, 6),
    (4, 0.5, 0.0, 8),
    (4, 0.5, math.pi, 8),
    (4, 0.25, 0.0, 12),
    (4, 0.25, math.pi, 12),
    (4, 0.75, math.pi, 12),
    (4, (2 - math.sqrt(3))/2, math.pi/2, 12),
    (4, (2 - math.sqrt(3))/2, 3*math.pi/2, 12),
    (4, (2 - math.sqrt(2))/4, 0.0, 16),
    (4, (2 + math.sqrt(2))/4, 0.0, 16),
    (4, (2 - math.sqrt(2))/2, math.pi/2, 16),
    (4, (3 - math.sqrt(5))/8, 0.0, 20),
    (4, (3 + math.sqrt(5))/8, 0.0, 20),
    (4, (5 - math.sqrt(5))/8, math.pi, 20),
    (4, (2 - math.sqrt(3))/4, 0.0, 24),
    (4, (2 + math.sqrt(3))/4, 0.0, 24),
    (4, 0.5, math.pi/2, 24),
    (4, 0.5, 3*math.pi/2, 24),

    # k = 5, 10
    (5, (5 - math.sqrt(5))/10, 0.0, 60),
    (5, (5 - math.sqrt(5))/10, 2*math.pi/5, 60),
    (5, (5 - math.sqrt(5))/10, 4*math.pi/5, 60),
    (5, (5 - math.sqrt(5))/10, 6*math.pi/5, 60),
    (5, (5 - math.sqrt(5))/10, 8*math.pi/5, 60),
    (5, (5 + math.sqrt(5))/10, 0.0, 60),
    (5, (5 + math.sqrt(5))/10, 2*math.pi/5, 60),
    (5, (5 + math.sqrt(5))/10, 4*math.pi/5, 60),
    (5, (5 + math.sqrt(5))/10, 6*math.pi/5, 60),
    (5, (5 + math.sqrt(5))/10, 8*math.pi/5, 60),

    # k = 6 (inherited from k = 3)
    (6, 2.0/3.0, 0.0, 8),
    (6, (5 - math.sqrt(5))/6, 0.0, 10),
    (6, 1.0/3.0, 0.0, 12),
    (6, (2 - math.sqrt(2))/3, 0.0, 16),

    # k = 8
    (8, 0.5, 0.0, 24),
    (8, 0.5, math.pi/2, 24),
    (8, 0.5, math.pi, 24),
    (8, 0.5, 3*math.pi/2, 24),

    # k = 10 (inherited from k = 5)
    (10, (5 - math.sqrt(5))/10, 0.0, 60),
    (10, (5 + math.sqrt(5))/10, 0.0, 60),
]
KNOWN_NON_REVIVALS_K = [7, 9, 11, 12, 16]


# ---------------------------------------------------------------------------
# Physics engine
# ---------------------------------------------------------------------------

def construct_U_k(k, rho, delta):
    C = np.array(
        [
            [np.sqrt(rho),              np.sqrt(1 - rho) * np.exp(1j * delta)],
            [np.sqrt(1 - rho),         -np.sqrt(rho)     * np.exp(1j * delta)],
        ],
        dtype=complex,
    )
    S = np.zeros((2 * k, 2 * k), dtype=complex)
    for i in range(k):
        S[2 * ((i - 1) % k) + 0, 2 * i + 0] = 1.0
        S[2 * ((i + 1) % k) + 1, 2 * i + 1] = 1.0
    return S @ np.kron(np.eye(k), C)


def eigenvalues_of(k, rho, delta):
    try:
        U = construct_U_k(k, rho, delta)
        return np.linalg.eigvals(U)
    except Exception:
        return None


def residual_for_N(eigs, N):
    target = 2 * np.pi / N
    worst = 0.0
    for z in eigs:
        ang = np.angle(z)
        m = round(ang / target)
        dev = abs(ang - m * target)
        if dev > worst:
            worst = dev
    return worst


def best_period(eigs, n_max=N_MAX):
    best_res = float("inf")
    best_N = None
    for N in range(1, n_max + 1):
        r = residual_for_N(eigs, N)
        if r < best_res:
            best_res = r
            best_N = N
            if r < 1e-14:
                break
    return best_N, best_res


def verify_by_matrix_power(k, rho, delta, N, tol=TOL_ACCEPT):
    U = construct_U_k(k, rho, delta)
    Up = np.linalg.matrix_power(U, N)
    diff = np.linalg.norm(Up - np.eye(2 * k, dtype=complex))
    return diff < tol, diff


def delta_distance(a, b):
    d = abs(a - b) % (2 * math.pi)
    return min(d, 2 * math.pi - d)


# ---------------------------------------------------------------------------
# Isolation and family tests
# ---------------------------------------------------------------------------

def is_isolated(k, rho, delta, N, width=ISOLATION_WIDTH):
    """
    True if revival at (rho, delta, N) is NOT part of a continuous
    family. Uses the tight TOL_FAMILY so that only genuine revivals
    count as neighbours.
    """
    eps = width / 2
    for r in (rho - eps, rho + eps):
        if r <= 1e-6 or r >= 1 - 1e-6:
            continue
        eigs = eigenvalues_of(k, r, delta)
        if eigs is None:
            continue
        if residual_for_N(eigs, N) < TOL_FAMILY:
            return False
    return True


def detect_family(k, delta, N):
    """
    True if revival at (k, delta, N) is continuous over rho. Uses the
    tight TOL_FAMILY so spurious near-misses do not count as families.
    """
    samples = (0.2, 0.35, 0.5, 0.65, 0.8)
    for rho in samples:
        eigs = eigenvalues_of(k, rho, delta)
        if eigs is None:
            return False
        if residual_for_N(eigs, N) > TOL_FAMILY:
            return False
    return True


# ---------------------------------------------------------------------------
# Stage 0 — physics engine sanity
# ---------------------------------------------------------------------------

def stage_0_sanity():
    print("=" * 72)
    print("STAGE 0: physics engine sanity checks")
    print("=" * 72)
    ok = True
    for (k, rho, delta, N) in KNOWN_REVIVALS:
        U = construct_U_k(k, rho, delta)
        unit_diff = np.linalg.norm(U @ U.conj().T - np.eye(2 * k))
        if unit_diff > 1e-10:
            print(f"  FAIL: U_k not unitary for k={k} (diff={unit_diff:.2e})")
            ok = False
            continue
        passed, diff = verify_by_matrix_power(k, rho, delta, N)
        status = "PASS" if passed else "FAIL"
        print(f"  {status}: k={k:2d}  rho={rho:.6f}  "
              f"delta={delta:.4f}  N={N:3d}  ||U^N-I||={diff:.2e}")
        if not passed:
            ok = False
    print("\n  All known revivals verified. Physics engine OK." if ok
          else "\n  Some checks FAILED.")
    print()
    return ok


# ---------------------------------------------------------------------------
# Refinement: coarse minimize + fine local sweep
# ---------------------------------------------------------------------------

def refine_rho(k, rho_seed, delta, N, span=1e-8, n_local=400):
    """
    Coarse minimization followed by a fine local sweep. Reaches
    residuals around 1e-14 for genuine revivals.
    """
    def objective(rho):
        if rho <= 1e-12 or rho >= 1 - 1e-12:
            return 1e3
        eigs = eigenvalues_of(k, rho, delta)
        if eigs is None:
            return 1e3
        return residual_for_N(eigs, N)

    lo = max(1e-6, rho_seed - 0.05)
    hi = min(1 - 1e-6, rho_seed + 0.05)
    try:
        res = minimize_scalar(objective, bounds=(lo, hi), method="bounded",
                              options={"xatol": 1e-15})
        rho_coarse = float(res.x)
        best_res = float(res.fun)
        best_rho = rho_coarse
    except Exception:
        rho_coarse = rho_seed
        best_rho = rho_seed
        best_res = objective(rho_seed)

    fine_lo = max(1e-12, rho_coarse - span)
    fine_hi = min(1 - 1e-12, rho_coarse + span)
    rhos = np.linspace(fine_lo, fine_hi, n_local)
    for r in rhos:
        rv = objective(r)
        if rv < best_res:
            best_res = rv
            best_rho = float(r)

    return best_rho, best_res, n_local


# ---------------------------------------------------------------------------
# Stage 2 — search one k
# ---------------------------------------------------------------------------

def stage_2_search_k(k, verbose=True):
    raw = []
    family_keys = set()

    for i in range(1, RHO_STEPS):
        rho = i / RHO_STEPS
        for delta in DELTA_LIST:
            eigs = eigenvalues_of(k, rho, delta)
            if eigs is None:
                continue
            N, res = best_period(eigs)
            if N is None:
                continue

            key = (N, round(delta, 12))

            # Family check: collapse a continuous plateau to one entry.
            if key not in family_keys and detect_family(k, delta, N):
                family_keys.add(key)
                raw.append((N, 0.5, delta, 0.0, "family"))
                continue
            if key in family_keys:
                continue

            # Grid hit — verify and check isolation.
            if res < TOL_ACCEPT:
                passed, _ = verify_by_matrix_power(k, rho, delta, N)
                if passed and is_isolated(k, rho, delta, N):
                    raw.append((N, rho, delta, res, "grid"))
                continue

            # Near miss → refine
            if res < SEED_TOL:
                rho_ref, res_ref, _ = refine_rho(k, rho, delta, N)
                if res_ref < TOL_ACCEPT:
                    passed, _ = verify_by_matrix_power(k, rho_ref, delta, N)
                    if passed and is_isolated(k, rho_ref, delta, N):
                        raw.append((N, rho_ref, delta, res_ref, "refine"))

    # Deduplicate (delta modulo 2*pi)
    unique = []
    for entry in sorted(raw):
        N, rho, delta, _, _ = entry
        dup = False
        for (Nu, rhou, du) in unique:
            if (Nu == N and
                abs(rhou - rho) < DEDUP_RHO and
                delta_distance(du, delta) < DEDUP_DELTA):
                dup = True
                break
        if not dup:
            unique.append((N, rho, delta))

    if verbose:
        counts = {}
        for e in raw:
            counts[e[4]] = counts.get(e[4], 0) + 1
        detail = ", ".join(f"{c} {s}" for s, c in counts.items()) or "none"
        print(f"  k={k:2d}: {len(raw):5d} raw ({detail}) "
              f"→ {len(unique):3d} unique")

    return unique


# ---------------------------------------------------------------------------
# Stage 3 — validation
# ---------------------------------------------------------------------------

def stage_3_validate(all_results):
    print()
    print("=" * 72)
    print("STAGE 3: validation against known revivals")
    print("=" * 72)
    ok = True
    for (k, rho, delta, N) in KNOWN_REVIVALS:
        hits = all_results.get(k, [])
        found = any(
            Nd == N and abs(rho_d - rho) < 1e-3
            and delta_distance(delta_d, delta) < 1e-6
            for (Nd, rho_d, delta_d) in hits
        )
        status = "PASS" if found else "FAIL"
        print(f"  {status}: k={k:2d}  rho={rho:.6f}  "
              f"delta={delta:.4f}  N={N:3d}")
        if not found:
            ok = False
    print("\n  All known revivals found." if ok
          else "\n  Some known revivals MISSED.")
    print()
    return ok


# ---------------------------------------------------------------------------
# Stage 4 — negative checks
# ---------------------------------------------------------------------------

def stage_4_negative(all_results):
    print("=" * 72)
    print("STAGE 4: negative checks (should be empty)")
    print("=" * 72)
    ok = True
    for k in KNOWN_NON_REVIVALS_K:
        hits = all_results.get(k, [])
        if hits:
            print(f"  UNEXPECTED: k={k:2d} has {len(hits)} families:")
            for (N, rho, delta) in hits[:5]:
                print(f"      N={N} rho={rho:.9f} delta={delta/math.pi:.4f}pi")
            if len(hits) > 5:
                print(f"      ... and {len(hits) - 5} more")
            ok = False
        else:
            print(f"  PASS: k={k:2d} has no revival on the search grid")
    print()
    return ok


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def write_outputs(all_results, meta):
    payload = {
        "meta": meta,
        "results": {
            str(k): [{"N": int(N), "rho": float(rho), "delta": float(delta)}
                     for (N, rho, delta) in v]
            for k, v in all_results.items()
        },
    }
    OUT_JSON.write_text(json.dumps(payload, indent=2))

    lines = [
        "% Auto-generated by exp025c-v6-rebuild.py (v4)",
        "\\begin{tabular}{r r l l}", "\\toprule",
        "$k$ & $N$ & $\\rho$ & $\\delta/\\pi$ \\\\", "\\midrule",
    ]
    for k in sorted(all_results):
        for (N, rho, delta) in all_results[k]:
            lines.append(
                f"{k} & {N} & ${rho:.9f}$ & ${delta/math.pi:.4f}$ \\\\"
            )
    lines += ["\\bottomrule", "\\end{tabular}"]
    OUT_TEX.write_text("\n".join(lines))
    print(f"Wrote {OUT_JSON}")
    print(f"Wrote {OUT_TEX}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 72)
    print("exp025c-v6-rebuild (v4): split-tolerance revival search")
    print("=" * 72)
    print(f"QUICK_TEST      = {QUICK_TEST}   (QUICK_K = {QUICK_K})")
    print(f"N_MAX           = {N_MAX}")
    print(f"RHO_STEPS       = {RHO_STEPS}   (Δρ = {1/RHO_STEPS:.2e})")
    print(f"DELTA_LIST      = {len(DELTA_LIST)} values of π-multiples")
    print(f"TOL_ACCEPT      = {TOL_ACCEPT:.1e}")
    print(f"TOL_FAMILY      = {TOL_FAMILY:.1e}")
    print(f"SEED_TOL        = {SEED_TOL:.1e}")
    print(f"DEDUP_RHO       = {DEDUP_RHO:.1e}")
    print(f"ISOLATION_WIDTH = {ISOLATION_WIDTH:.3f}")
    print(f"OUT_JSON        = {OUT_JSON}")
    print(f"OUT_TEX         = {OUT_TEX}")
    print()

    if not stage_0_sanity():
        print("Aborting after Stage 0.")
        return

    if QUICK_TEST:
        k = QUICK_K
        print("=" * 72)
        print(f"STAGE 2 (QUICK TEST): k = {k} only")
        print("=" * 72)

        # Manual check of a known revival at this k (if available)
        for (kk, rho_known, delta_known, N_known) in KNOWN_REVIVALS:
            if kk == k:
                print(f"\n[Debug] Manual check at k={k}, rho={rho_known:.6f}, "
                      f"delta={delta_known}, N={N_known}:")
                eigs = eigenvalues_of(k, rho_known, delta_known)
                print(f"  residual N={N_known}: "
                      f"{residual_for_N(eigs, N_known):.3e}")
                print(f"  verify U^N=I: "
                      f"{verify_by_matrix_power(k, rho_known, delta_known, N_known)}")
                break

        print(f"\n[Debug] Running search for k={k}:")
        hits = stage_2_search_k(k)
        print(f"\nk={k} total families: {len(hits)}")
        for (N, rho, delta) in hits[:40]:
            print(f"  N={N:3d}  rho={rho:.9f}  delta={delta/math.pi:.4f}pi")
        if len(hits) > 40:
            print(f"  ... and {len(hits) - 40} more")
        return

    print("=" * 72)
    print("STAGE 2: search over all k")
    print("=" * 72)
    K_LIST = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    all_results = {}
    for k in K_LIST:
        hits = stage_2_search_k(k)
        all_results[k] = hits

    stage_3_validate(all_results)
    stage_4_negative(all_results)

    print("=" * 72)
    print("SUMMARY")
    print("=" * 72)
    for k in K_LIST:
        hits = all_results[k]
        if hits:
            periods = sorted({N for (N, _, _) in hits})
            print(f"  k={k:2d}: {len(hits):3d} families, N ∈ {periods}")
        else:
            print(f"  k={k:2d}: no revival found")

    meta = {
        "N_MAX": N_MAX,
        "RHO_STEPS": RHO_STEPS,
        "RHO_RESOLUTION": 1 / RHO_STEPS,
        "DELTA_MULTIPLES": [str(m) for m in DELTA_MULTIPLES],
        "TOL_ACCEPT": TOL_ACCEPT,
        "TOL_FAMILY": TOL_FAMILY,
        "SEED_TOL": SEED_TOL,
        "DEDUP_RHO": DEDUP_RHO,
        "ISOLATION_WIDTH": ISOLATION_WIDTH,
        "K_LIST": K_LIST,
    }
    print()
    write_outputs(all_results, meta)


if __name__ == "__main__":
    main()

!find /content -name "exp025c-v6*" -ls 2>/dev/null

!mkdir -p /content/drive/MyDrive/modular-latex
!cp /content/exp025c-v6-output.json /content/drive/MyDrive/modular-latex/
!cp /content/exp025c-v6-table.tex /content/drive/MyDrive/modular-latex/
!ls -la /content/drive/MyDrive/modular-latex/exp025c-v6*